### ISSUE TITLE
Whole display as on/off button

### ISSUE THREAD

**Issue by JohnVeness** [sanbeg/flashlight#3]
Thanks for the app, which works great on my Sony Xperia Pro.

Could you consider enlarging the on/off button, using the entire display? That way it could be turned off and on without looking at the screen.

**Comment by sanbeg** [comment]
I've updated it to turn on/off with a long press on the background.  That should make it easy to switch with less chance of an accidental button press.

**Comment by JohnVeness** [comment]
Thanks for the fix. I see the new version in Google Play. However, I don't see a source code commit for this in github.

**Comment by sanbeg** [comment]
I'm currently working off the studio branch,  until I sort out which files
to ignore and how to cleanly merge an orphan branch.

**Comment by JohnVeness** [comment]
I know I requested this feature and you kidnly implemented it, but I'm finding in practice this may be a case of "be careful what you wish for". Even with it having to be a long press to toggle the flashlight, I find I am accidentally turning it off and on too easily, just while holding the device. I have quite a large bezel so it would be even worse for Galaxy S6 Edge users and similar.

I'm not sure what the best solution is, although I did find the old behaviour of a small button in the middle a little too fiddly to press. Maybe you could remove the whole-screen press, and just make the button in the middle bigger.
